[versions]
# ksp: https://github.com/google/ksp/releases
# compose-compiler: https://developer.android.com/jetpack/androidx/releases/compose-compiler
# hilt: https://github.com/google/dagger/releases

# Project
androidGradlePlugin = "8.11.1"
kotlin = "2.2.0"
ksp = "2.2.0-2.0.2"

compose_compiler = "1.5.15"
version_code = "20007"
version_name = "2.0.7"
android_sdk_compile = "36"
android_sdk_target = "35"
android_sdk_min = "26"

# Hilt
hilt = "2.57"
hiltCompose = "1.2.0"
hiltWorker = "1.2.0"

# Compose
composeBom = "2025.08.00"

# AndroidX
corektx = "1.16.0"
appcompat = "1.7.1"
activity = "1.10.1"
material = "1.12.0"
datastore="1.1.7"
constraintLayout = "1.1.1"
androidxLifecycle = "2.9.2"
composeNavigation = "2.9.3"

activityCompose = "1.12.0-alpha06"
material3 = "1.4.0-beta01"
navigation3 = "1.0.0-alpha07"
navigation3Material = "1.0.0-SNAPSHOT"
lifecycleViewmodel = "1.0.0-SNAPSHOT"

palette = "1.0.0"

# Media3
media3 = "1.8.0"
mediarouter = "1.8.1"

# KotlinX
kotlinxCoroutines = "1.10.2"
kotlinxSerialization = "1.9.0"
kotlinxImmutable = "0.4.0"

# JavaX
javaxInject = "1"

# work
work = "2.10.3"

# Room
room = "2.7.2"

# Network
retrofit = "3.0.0"
retrofit-mock = "3.0.0"
retrofit-interceptor = "5.1.0"
chucker = "4.2.0"
retrofit-serialization-converter = "1.0.0"

# Glide
glide = "4.16.0"
glideCompose = "1.0.0-beta01"

## license
# https://developers.google.com/android/guides/opensource
ossLicenses = "17.2.2"
ossLicensesPlugin = "0.10.7"

# Timber
timber ="5.0.1"
processPhoenix = "3.0.0"

# Ted-permission
tedpermission = "3.4.2"

# Lottie
lottie = "6.6.7"

# AudioFileIO
jaudiotagger = "2.3.15"

# Leak canary
leakCanary = "2.14"
detekt = "1.23.8" # https://github.com/detekt/detekt

# Test
testJunit = "4.13.2"
junitVintageEngine = "5.13.4"
kotest = "6.0.0"
mockk = "1.14.5"
turbine = "1.2.1"

# AndroidTest
androidxTestExt = "1.3.0"
androidxEspresso = "3.7.0"
junit = "1.1.5"

[libraries]
# plugin
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
verify-detekt-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
oss-licenses-plugin = { group = "com.google.android.gms", name = "oss-licenses-plugin", version.ref = "ossLicensesPlugin" }

# Hilt
hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

hilt-androidx-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltCompose" }
hilt-androidx-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltWorker" }
hilt-androidx-work-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltWorker" }

# work
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work"}
androidx-work-testing = { group = "androidx.work", name = "work-testing", version.ref = "work" }

# Room
androidx-room = { group = "androidx.room", name = "room-runtime", version.ref = "room"}
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room"}
androidx-room-compile = { group = "androidx.room", name = "room-compiler", version.ref = "room"}

# JavaX
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javaxInject" }

# KotlinX
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxImmutable" }

# AndroidX
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "corektx" }
androidx-material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }

androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }

androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintLayout" }
androidx-datastore-preference = {module = "androidx.datastore:datastore-preferences", version.ref ="datastore"}

# verify
verify-detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

# Compose BOM
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }

# Compose UI
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview-build = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

# Compose navigation
androidx-compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }
androidx-compose-navigation-test = { group = "androidx.navigation", name = "navigation-testing", version.ref = "composeNavigation" }

androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "navigation3" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "navigation3" }
androidx-material3-navigation3 = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "navigation3Material" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodel" }

# Compose Material
#androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }

# Compose Material3
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-materialWindow = { group = "androidx.compose.material3", name = "material3-window-size-class" }

# palette
androidx-palette = { module = "androidx.palette:palette", version.ref = "palette" }

# license
oss-licenses = { group = "com.google.android.gms", name = "play-services-oss-licenses", version.ref = "ossLicenses" }

# Media3 - ExoPlayer
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
androidx-media3-hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "media3" }
androidx-media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
androidx-media3-common = { group = "androidx.media3", name = "media3-common", version.ref = "media3" }
androidx-mediarouter = { module = "androidx.mediarouter:mediarouter", version.ref = "mediarouter"}

# Network
squareup-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit"}
squareup-retrofit-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit"}
squareup-retrofit-mock = { group = "com.squareup.retrofit2", name = "retrofit-mock", version.ref = "retrofit-mock"}
squareup-retrofit-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "retrofit-interceptor"}

# converter
jakewharton-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit-serialization-converter"}
squareup-retrofit-scalars-converter = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "retrofit"}

# chucker
chucker-debug = { group = "com.github.chuckerteam.chucker", name = "library", version.ref = "chucker"}
chucker-release = { group = "com.github.chuckerteam.chucker",name = "library-no-op", version.ref = "chucker"}

# Glide
bumptech-glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide"}
bumptech-glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide"}
bumptech-glide-compose = { group = "com.github.bumptech.glide", name = "compose", version.ref = "glideCompose"}

# Timber
jakewharton-timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
jakewharton-process-phoenix = { module = "com.jakewharton:process-phoenix", version.ref = "processPhoenix" }

# Leark canary
squareup-leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }

# Lottie
airbnb-android-lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie"}

# tedpermission
tedpermission-coroutine = { module = "io.github.ParkSangGwon:tedpermission-coroutine", version.ref = "tedpermission"}

# audioFileIO
jaudiotagger = { module = "com.github.Adonai:jaudiotagger", version.ref = "jaudiotagger" }

# Test
junit4 = { group = "junit", name = "junit", version.ref = "testJunit" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
junit-vintage-engine = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junitVintageEngine" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
kotest-runner = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
#junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }